### ISSUE TITLE
Decimal value on the progress-bar

### ISSUE THREAD

**Issue by SoumyaBindhani** [mendixlabs/progress-bar#9]
Currently, the widget rounds up the decimal value(90.45, 90.61) to nearest integer value(90 & 91 respectively). Even though progress-bar accepts floats and decimal values, I can't make use of that data type in front end. So is there a way I can get to see the decimal points as well in front end? It can be one decimal point or two. Kindly, have a thought. Thank you.

**Comment by Andries-Smit** [comment]
Dear Soumya,

At the moment there is no way of showing the decimals in the frontend. We are currently reviewing a more flexible solution for the progress bar and progress circle show text.

We will keep you posted.

Cheers, Andries

**Comment by Andries-Smit** [comment]
Dear Soumya,

We add the text attribute for the progress bar widget v1.2.0 , this way you can create a text to you specification.  Available trough the app store https://appstore.home.mendix.com/link/app/48910/

Cheers, Andries
